version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.debug.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - qiwi-pay-network
    depends_on:
      - jwt-server

  jwt-server:
    build:
      context: jwt-server
      dockerfile: jwt.dockerfile
    container_name: jwt-server
    restart: always
    environment:
      - PORT=9096
      - AEROSPIKE_HOST=aerospike
      - AEROSPIKE_PORT=3000
      - PG_USER=root
      - PG_PASSWORD=root_pg
      - PG_HOST=pg_db
      - PG_DB=qiwi-pay
      - PG_USER_TABLE=users
      - PG_LOGIN_FIELD=phone
      - ALLOWED_ACCESSES=qr_create:user|pays:user|bill:merchant|bill_get:merchant
    networks:
      - qiwi-pay-network
    depends_on:
      - aerospike
      - pg_db

  merchant-server:
    build:
      context: merchant-server
      dockerfile: merchant.dockerfile
    container_name: merchant-server
    restart: always
    environment:
      - PORT=9096
      - PG_USER=root
      - PG_PASSWORD=root_pg
      - PG_HOST=pg_db
      - PG_DB=qiwi-pay
      - PG_USER_TABLE=users
    networks:
      - qiwi-pay-network
    depends_on:
      - pg_db

  client-server:
    build:
      context: client-server
      dockerfile: client.dockerfile
    container_name: client-server
    restart: always
    environment:
      - PORT=9096
      - PG_USER=root
      - PG_PASSWORD=root_pg
      - PG_HOST=pg_db
      - PG_DB=qiwi-pay
      - PG_USER_TABLE=users
    networks:
      - qiwi-pay-network
    depends_on:
      - pg_db

  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server
    restart: always
    networks:
      - qiwi-pay-network

  pg_db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_pg
      - POSTGRES_DB=qiwi-pay
    volumes:
      - db_pg_qiwi:/var/lib/postgresql/data/
      - ./docker/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    container_name: pg_db
    networks:
      - qiwi-pay-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8001:8080"
    container_name: adminer
    networks:
      - qiwi-pay-network

networks:
  qiwi-pay-network:
    driver: bridge

volumes:
  db_pg_qiwi: